### ISSUE TITLE
ComponentName field recognises only when the component is registered globally

### ISSUE THREAD

**Issue by Alosies** [huangshuwei/vue-easytable#141]
In Vue single file components, I created a child component and imported it to the parent component where I display the table using <v-table></v-table> tag.

The image of the relevant part of the code is given below
<img width="695" alt="screen shot 2018-04-05 at 9 41 04 am" src="https://user-images.githubusercontent.com/24241029/38346906-999bd23e-38b5-11e8-9e99-5c1453785992.png">

**Child component not rendered inside the table**
But the component is not getting rendered within the cell. And I get error in the console as
<img width="359" alt="screen shot 2018-04-05 at 9 44 25 am" src="https://user-images.githubusercontent.com/24241029/38346968-f8f4644e-38b5-11e8-9862-e0f5c4d6d33e.png">

I am able to verify that the child component is registered correctly in the parent by rendering it successfully outside the table like so
Parent Component code:
<img width="794" alt="screen shot 2018-04-05 at 9 49 39 am" src="https://user-images.githubusercontent.com/24241029/38347089-c4d3d8ec-38b6-11e8-83c8-53590bbfc38b.png">

Rendering in the browser:
<img width="1011" alt="screen shot 2018-04-05 at 9 50 41 am" src="https://user-images.githubusercontent.com/24241029/38347109-e8add2a4-38b6-11e8-83db-3cf059de5f16.png">

**Renders correctly when Child component is registered globally**
However, when I register the child component globally in main.js, it renders correctly.
<img width="1016" alt="screen shot 2018-04-05 at 9 56 20 am" src="https://user-images.githubusercontent.com/24241029/38347204-a44beeba-38b7-11e8-97e4-7e1fa855432f.png">

Can you please show how I can achieve the same by registering locally inside the parent

**Comment by ly525** [comment]
@Alosies @mistyrain98 
Hi, I read the source code and got some advices that may be helpful for you

[source code link ](https://github.com/huangshuwei/vue-easytable/blob/1a148ef8af76190fcb796c65e3d3e6874da34e96/packages/v-table/src/table.vue#L147)

```
<component 
  :rowData="item" 
  :field="col.field ? col.field : ''"
  :index="rowIndex" 
  :is="col.componentName"
  @on-custom-comp="customCompFunc">
</component>
```

1. Util now, you need to register the component globally, the local registration will not work.
2. Because `easy-table` is a sub component of your single vue file component, as the [vue-docs](https://vuejs.org/v2/guide/components-registration.html#Local-Registration) mentioned: `Note that locally registered components are not also available in subcomponents.`. So you need to register the component globally to custom the column.
3. I do not read the source code about `<component is></component>` of Vue.js,  I will read later, and perfect the answer. 
4. I guess, the `is` property (dynamic component) need globally registered component, but I am not sure.

---

中文解释(Chinese Explanation)
我读了源码，希望能够下面的解答能够有所帮助
[源码链接] ([source code link ](https://github.com/huangshuwei/vue-easytable/blob/1a148ef8af76190fcb796c65e3d3e6874da34e96/packages/v-table/src/table.vue#L147))

1. 到现在为止，你需要全局注册组件，局部注册不行
2. 原因是 `easy-table` 是你单个 vue 文件的子组件，正如 Vue.js 官方文档中提及的：`注意局部注册的组件在其子组件中不可用`, 所以你需要注册全局组件，来实现自定义列
3. 我还没有阅读 Vue.js 源码中关于 `<component is></component>` 的这部分，回头我会看下这部分的实现，之后再来完善这个回答
4. 个人猜测，`is` (动态组件) 需要使用全局注册使用

**Comment by huangshuwei** [comment]
The new version has solved this problem.

Please use [version 2.0](https://github.com/huangshuwei/vue-easytable/releases/tag/2.0.0)
